version: '3.7'

services:
  mongo:
    image: mongo:4.2.3
    container_name: ${MONGO_INITDB_CONTAINER}
    restart: always
    env_file:
      - .env
    volumes:
      - ./etc/mongodb:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db

  redis:
    image: redis:5.0.8-alpine
    container_name: ${REDIS_CONTAINER}
    env_file:
      - .env
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}'

volumes:
  mongodb_data: