version: '3.7'

services:
  mongo:
    image: mongo:4.2.3
    container_name: ${MONGO_INITDB_CONTAINER}
    restart: always
    env_file:
      - .env
    volumes:
      - ./etc/mongodb:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo "mongodb://${MONGO_INITDB_USERNAME}:${MONGO_INITDB_PASSWORD}@${MONGO_INITDB_CONTAINER}:${MONGO_INITDB_PORT}/${MONGO_INITDB_DATABASE}" --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  redis:
    image: redis:5.0.8-alpine
    container_name: ${REDIS_CONTAINER}
    env_file:
      - .env
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data: