version: '3.7'

services:

  auth-service:
    image: docker.pkg.github.com/cv65kr/auth-service
    container_name: auth-service
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis