version: '3.7'

services:

  auth-service:
    image: docker.pkg.github.com/cv65kr/authorization-service/authorization-service
    container_name: auth-service
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - redis