version: '3.7'

services:
  mongo:
    image: mongo:4.2.3
    restart: always
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./etc/mongodb:/docker-entrypoint-initdb.d
      - mongodb_data:/data/db

  redis:
    image: redis:5.0.8-alpine
    env_file:
      - .env
    ports:
      - "6379:6379"
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}'

volumes:
  mongodb_data: