name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build depend containers
        run: make env=dev start;
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test and build application
        run: make env=dev test;make env=dev package;
        env:
          APP_ENV: dev
          MONGO_INITDB_CONTAINER: mongodb
          MONGO_INITDB_DATABASE: users
          MONGO_INITDB_USERNAME: user
          MONGO_INITDB_PASSWORD: pass
          MONGO_INITDB_PORT: 27017
          REDIS_CONTAINER: redis
          REDIS_PORT: 6379
          REDIS_PASSWORD: redis123
      - name: Publish to github registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: docker.pkg.github.com
          name: cv65kr/authorization-service/authorization-service
          username: ${{ github.actor }}
          password: ${{ github.token }}
          tag_semver: true